spring:
  r2dbc:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}


Phantom:
  apiKey: ${PHANTOM_API_KEY}
  baseUrl: "https://api.phantombuster.com/api/v2"
  linkedInUrl: "https://www.linkedin.com/search/results/people/?keywords="
  agentId: "1996040450520958"
  sessionCookie: ${SESSION_COOKIE}
